#!/usr/bin/env python3
"""Vendor the icons listed in tools/icons.manifest into the package.

Each manifest entry ``<id> <phosphor-name> <weight>`` is copied from the local
Phosphor asset directory to::

    linfilecopy/data/icons/hicolor/scalable/actions/lfc-<id>-symbolic.svg

The ``-symbolic`` suffix makes GTK recolour the icon with the theme's
foreground colour, and the ``lfc-`` prefix keeps our names from colliding with
any system icon theme. The vendored files are committed, so building the app
never needs the asset directory. Phosphor's MIT licence and a generated
ICONS.md are written alongside.

Usage:
    python3 tools/vendor_icons.py [--icons DIR] [--check]

``--check`` verifies the vendored set is complete and current without writing.
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from build_mockups import DEFAULT_ICON_DIR, read_manifest  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
DEST = ROOT / "linfilecopy" / "data" / "icons" / "hicolor" / "scalable" / "actions"
ICON_DOC = ROOT / "linfilecopy" / "data" / "icons" / "ICONS.md"
LICENSE_DEST = ROOT / "linfilecopy" / "data" / "icons" / "LICENSE-phosphor"

# GTK 3 recolours symbolic SVGs by forcing a fill on these element types.
ALLOWED_ELEMENTS = {"svg", "path", "rect", "circle", "ellipse", "polygon", "g"}
ELEMENT_RE = re.compile(r"<([a-zA-Z][\w:-]*)")


def normalise(svg: str) -> str:
    """Return the SVG with an explicit 16x16 size so GTK sizes it predictably."""
    svg = svg.strip()
    if "width=" not in svg.split(">", 1)[0]:
        svg = svg.replace("<svg ", '<svg width="16" height="16" ', 1)
    return svg + "\n"


def vendor(icon_dir: Path, check: bool) -> int:
    """Copy (or verify) every manifest icon. Returns the number of problems."""
    entries = read_manifest()
    problems = 0
    expected: set[str] = set()
    DEST.mkdir(parents=True, exist_ok=True)
    for entry in entries.values():
        src = entry.source_path(icon_dir)
        target = DEST / f"lfc-{entry.semantic_id}-symbolic.svg"
        expected.add(target.name)
        if not src.is_file():
            print(f"missing source: {src}")
            problems += 1
            continue
        data = src.read_text(encoding="utf-8")
        bad = {e for e in ELEMENT_RE.findall(data) if e not in ALLOWED_ELEMENTS}
        if bad:
            print(f"{src.name}: unsupported elements for symbolic recolouring: {sorted(bad)}")
            problems += 1
        content = normalise(data)
        if check:
            if not target.is_file() or target.read_text(encoding="utf-8") != content:
                print(f"out of date: {target.relative_to(ROOT)}")
                problems += 1
        else:
            target.write_text(content, encoding="utf-8")

    stale = sorted(p.name for p in DEST.glob("lfc-*-symbolic.svg") if p.name not in expected)
    for name in stale:
        if check:
            print(f"stale icon not in manifest: {name}")
            problems += 1
        else:
            (DEST / name).unlink()

    if not check:
        LICENSE_DEST.write_text((icon_dir / "LICENSE").read_text(encoding="utf-8"), encoding="utf-8")
        lines = [
            "# Vendored icons",
            "",
            "Generated by `tools/vendor_icons.py` from `tools/icons.manifest`.",
            "Source: Phosphor Icons v2.0.8 (MIT, see LICENSE-phosphor).",
            "",
            "| Icon name | Phosphor | Weight | Purpose |",
            "|---|---|---|---|",
        ]
        lines += [
            f"| `lfc-{e.semantic_id}-symbolic` | {e.phosphor} | {e.weight} | {e.purpose} |"
            for e in entries.values()
        ]
        ICON_DOC.write_text("\n".join(lines) + "\n", encoding="utf-8")
        print(f"vendored {len(entries)} icons into {DEST.relative_to(ROOT)}")
    return problems


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--icons", type=Path, default=DEFAULT_ICON_DIR, help="Phosphor asset directory")
    parser.add_argument("--check", action="store_true", help="verify without writing")
    args = parser.parse_args(argv)
    problems = vendor(args.icons, args.check)
    return 1 if problems else 0


if __name__ == "__main__":
    sys.exit(main())
